### ISSUE TITLE
how to build with lua 5.3

### ISSUE THREAD

**Issue by dingmingxin** [pkulchenko/wxlua#1]
how to build wxlua with lua version 5.3 and version of wxwidges is 3.1.0

**Comment by pkulchenko** [comment]
@dingmingxin, I don't think you need anything special. Just make sure that your Lua 5.3 is compiled with `LUA_COMPAT_MODULE` and `LUA_LIBRARY` points to the location of lua53.dll:

```
-DCMAKE_CXX_FLAGS="-DLUA_COMPAT_MODULE"
-DwxLua_LUA_LIBRARY="somewhere/lib/lua53.dll"
```

See https://sourceforge.net/p/wxlua/mailman/message/35138574/ for the related discussion.
