### ISSUE TITLE
GetCPUCount

### ISSUE THREAD

**Issue by sonoro1234** [pkulchenko/wxlua#104]
Hi,

Would it be possible to bind wxThread:GetCPUCount ?

Thanks

**Comment by pkulchenko** [comment]
@sonoro1234, I don't think there is any support for `wxThread` in wxlua, so it will have to be added first to add `GetCPUCount`. Patches welcome ;).

**Comment by pkulchenko** [comment]
@sonoro1234, I'll close this one for now; feel free to reopen or continue the discussion if you have some suggestions on how to implement it.
