### ISSUE TITLE
Is there any consideration of wrapping Qt with Lua

### ISSUE THREAD

**Issue by louislau86** [pkulchenko/wxlua#105]

**Comment by louislau86** [comment]
Thanks for your good job of wxLua. 
Nowadays, many people use Qt as their GUI framwork, is there any consideration of wrapping Qt with lua in order to use lua develop Qt based apps?

**Comment by pkulchenko** [comment]
It looks like there is already https://github.com/lqt5/lqt and https://github.com/torch/qtlua, although I'm not familiar with either project. The API and the bindings are completely different and it's quite an undertaking to support, so I have no plans to do it as part of this project.
