### ISSUE TITLE
OpenGL core profile need two more class

### ISSUE THREAD

**Issue by wtjcn** [pkulchenko/wxlua#11]
to use OpenGL core profile, two more class are needed, wxGLAttributes and wxGLContextAttrs, as usded in   wxWidgets samples opengl/pyramid

**Comment by pkulchenko** [comment]
@wtjcn, I've added these two classes and also added some of the new methods to wxGLContext; all the changes have been pushed to https://github.com/pkulchenko/wxlua/tree/wxwidgets312.

Here is the sample code that works for me:

```lua
canvas = wx.wxGLCanvas(frame, wx.wxID_ANY, {}, wx.wxDefaultPosition, wx.wxDefaultSize, wx.wxEXPAND)

local attrs = wx.wxGLAttributes()
attrs:PlatformDefaults():Defaults():EndList()
print(canvas.IsDisplaySupported(attrs))
```
