### ISSUE TITLE
wxStEdit still used?

### ISSUE THREAD

**Issue by ildar** [pkulchenko/wxlua#114]
wxStEdit is mandatory for wxLua yet I don't see it's really used.
I don't see any of its trails in wx.so also.
Please clarify.

**Comment by pkulchenko** [comment]
@ildar, why do you believe it's mandatory for wxLua? It's used in wxLuaEdit, but it hasn't been supported in a long time and its functionality is covered by `samples/editor.wx.lua` script (and by [ZeroBrane Studio](https://studio.zerobrane.com)). I don't think there is anything I can do to address this.

**Comment by ildar** [comment]
Ah! I seem have missed the `(only for wxWidgets < 2.9)`
Thanks, closing.
