### ISSUE TITLE
Building wxLua against wxWidgets 3.2.2.1 using CMake and MSBuild with VS Code.

### ISSUE THREAD

**Issue by wan-may** [pkulchenko/wxlua#116]
I've compiled wxWidgets as a shared library (not monolithic), with the samples. I ran a few of them, they work fine.
The wxWidgets download is located in D:\bin\wxWidgets-3.2.2.1, and the output of that build is in D:\bin\wxWidgets-3.2.2.1\build\lib\vc_x64_dll.

Now, using the exact same IDE and compiler, I navigated to my wxLua folder, indicated the top level CMakeLists.txt there, indicated my system was x64, went into the CMake cache editor, set **wxWidgets_LIB_DIR** to D:/bin/wxWidgets-3.2.2.1/build/lib/vc_x64_dll, set **wxWidgets_ROOT_DIR** to D:\bin\wxWidgets-3.2.2.1, enabled **BUILD_SHARED_LIBS**, then hit Configure All three times.

On building I get the following sort of error:
`[build] wxlua\wxLua\modules\wxlua\dummy.cpp(20,10): fatal  error C1083: Impossible d'ouvrir le fichier include : 'wx/wxprec.h' : No such file or directory [D:\dev\aw7-native\wxlua\build\modules\wxlua\wxLuaLib.vcxproj]
`

I'm going nuts here, _why not?_ My wxWidgets_ROOT_DIR has an include/wx/wxprec.h in it. I couldn't understand the CMake script well enough to see what include directories the compiler is actually using.

please help

**Comment by pkulchenko** [comment]
I'd be glad to help, but I'm no cmake expert and don't have visual studio environment to build it with. I'm using mingw/msys configuration with the following "configure" command:

```
  cmake -G "MSYS Makefiles" -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" -DCMAKE_BUILD_TYPE=$WXLUABUILD -DBUILD_SHARED_LIBS=FALSE \
    -DCMAKE_CXX_FLAGS="-DLUA_COMPAT_MODULE" \
    -DwxWidgets_CONFIG_EXECUTABLE="$INSTALL_DIR/bin/wx-config" \
    -DwxWidgets_COMPONENTS="xrc;xml;stc;html;aui;adv;core;net;base" \
    -DwxLuaBind_COMPONENTS="xrc;xml;stc;html;aui;adv;core;net;base" \
    -DwxLua_LUA_LIBRARY_USE_BUILTIN=FALSE \
    -DwxLua_LUA_INCLUDE_DIR="$INSTALL_DIR/include" -DwxLua_LUA_LIBRARY="$INSTALL_DIR/lib/lua$LUAV.dll" .
```

The entire build script available here: https://github.com/pkulchenko/ZeroBraneStudio/blob/master/build/build-win32.sh#L309; see if this gives you any clue on how to solve it.

**Comment by wan-may** [comment]
I'll do my best to read it and post back here once I figure out what my problem is. Thank you!

**Comment by wan-may** [comment]
I just realized FindwxWidgets.cmake is actually part of CMake, rather than this project's CMake configuration.
Regardless of whether I ultimately solve this issue, it is probably outside the scope of wxLua.
