### ISSUE TITLE
wxRichTextCtrl not available

### ISSUE THREAD

**Issue by aryajur** [pkulchenko/wxlua#129]
Hi,
       Is wxRichTextControl available in the binding? I see some interface files but after compiling the latest release with the latest wxwidgets wx.wxRichTextCtrl is still nil. Do I need any extra step to enable it?

**Comment by pkulchenko** [comment]
@aryajur, yes, it should be, but you need to enable `richtext` as one of the components and make sure that wxwidgets is built with `--enable-richtext`:

```
    -DwxWidgets_COMPONENTS="richtext;xrc;xml;stc;gl;html;aui;adv;core;net;base" \
    -DwxLuaBind_COMPONENTS="richtext;xrc;xml;stc;gl;html;aui;adv;core;net;base" \
```

**Comment by aryajur** [comment]
Thank you!
