### ISSUE TITLE
Adding new items to the interface files

### ISSUE THREAD

**Issue by aryajur** [pkulchenko/wxlua#130]
Hi,
       I am trying to update the interface files which are missing some new functions and enumerations. Once I make the interface file changes do I have to run a binding generator script or does the build process does that automatically?
       Also this is not an issue, was not sure if there is an active mailing list for wxlua now?

**Comment by pkulchenko** [comment]
@aryajur, yes, after modifying the interface files you just need to run `genwxbind.bat` or `make` in `wxLua/bindings/`.

I also have `any-bind-sync.lua` and `stc-bind-sync.lua` scripts in the same folder, which may be useful in doing the bulk of the work to extend/update existing interfaces, although I'd review the generated interface files and fix as needed (let me know if you come up with any fixes for the scripts).

In terms of the maillist, `wxlua-users@lists.sourceforge.net` is still in use, although it's low traffic. I do respond to questions posted there and occasionally announce new versions.
