### ISSUE TITLE
Debugging doesn't work

### ISSUE THREAD

**Issue by fenix272** [pkulchenko/wxlua#132]
I compiled wxlua with wxwidgets 3.2.4 and luajit and all went fine, my wxlua app works. Now i'm trying to debug it but i can't. If i attach my app running first 'wxlua -dHOST:PORT myapp.lua' after clicking the attach menu button the wxlua process starts but no frame window appears. In the output window no message saying 'client connected ok'. If instead i click 'start debugging' the message 'client connected ok' appears but nothing else happens and all the menu buttons(step, step over, step out etc.) are disabled.

**Comment by fenix272** [comment]
Furthemore if i start my app with the -c flag in order to get printing messages with the print function, i get no message at all. Why? It's really difficult to debug it when i can't even get my own messages. Is there another way to get them?

**Comment by pkulchenko** [comment]
@fenix272, it's difficult for me to say what may be wrong. I ran into some issues with the debugger included into wxlua long time ago and since I was already working on a [lua-only debugger](https://github.com/pkulchenko/MobDebug) at that time, I didn't have time to focus on both. If you can figure out what's wrong, I'll definitely review and accept patches. If you're just interested in debugging your Lua scripts, you may want to check my wxlua-based [ZeroBrane Studio](https://github.com/pkulchenko/ZeroBraneStudio) debugger/IDE to see if you can make it working there.

**Comment by fenix272** [comment]
Thank you for your answer. I downloaded the ZeroBrane Studio IDE and i set the interpreter to wxlua and now i can debug my apps like a pro. Thank you again. If i may ask, how can i set the icon of my app? In c++ i use a resource file to do so. How can i do in  wxLua? Also, sometimes  some wxwidgets methods are not there. For example 'wxDisplay().GetGeometry().GetHeight()'.  In wxLua i tried wxDisplay.GetGeometry().GetHeight() but with no success. Is there a documentations which explain the differences?

**Comment by fenix272** [comment]
Well i solved the wxDisplay problem, i did: `  local gm = wx.wxDisplay():GetGeometry()
    local screenH = gm:GetHeight()
    local screenW = gm:GetWidth()`

**Comment by pkulchenko** [comment]
> `local gm = wx.wxDisplay():GetGeometry() local screenH = gm:GetHeight() local screenW = gm:GetWidth()`

That's correct, as wxDisplay is a class method (so uses `.` notation), but GetHeight and GetWidth are object methods (so need to use `:` notation). Usually everything that starts from `wx` would indicate a class method.

> If i may ask, how can i set the icon of my app? In c++ i use a resource file to do so. How can i do in wxLua?

Mostly the same way you'd do it in c++. Here is what I do in zbstudio.exe:
- I use winres to turn a resource file into an object file: https://github.com/pkulchenko/ZeroBraneStudio/blob/master/build/build-win32.sh#L426
- The [resource file](https://github.com/pkulchenko/ZeroBraneStudio/blob/master/zbstudio/res/zbstudio.rc) references the .ico file (in the same folder) and the manifest file (also in the same folder)
- The generated object file is then compiled into the executable: https://github.com/pkulchenko/ZeroBraneStudio/blob/master/build/build-win32.sh#L427.

In my case I use this file as a launcher with the actual wxlua code stored in the dll (so I don't need to recompile the launcher every time wxlua code is updated), but you can apply the same method when you statically compile. If you are on Linux or macOS, the process is different, but all the necessary files are in the same folder (see zbstudio.desktop for Linux and `zbstudio/ZeroBraneStudio.app` for macOS configurations).
