### ISSUE TITLE
Question WXLua Docupedia

### ISSUE THREAD

**Issue by Abooow786** [pkulchenko/wxlua#134]
Hello pkulchenko,

i worked a little bit with the ZEROBRANE IDE and it was the best thing ever:)
Now i wanted to build a own Program written in Lua and after some research i saw that you used WXLua. So i thought why not use it my self. But i can't find a Docupedia to it? [https://wxlua.sourceforge.net/documentation.php](url) is not working and i didnt find anything else in the internet? Is there another Page or a Backup?

Regards

**Comment by pkulchenko** [comment]
For those that may be looking at this ticket: the old links are not working, but all the documentation should still be available in this repository, for example: https://github.com/pkulchenko/wxlua/blob/master/wxLua/docs/binding.md. The details haven't been updated, but most of what's written should still apply (and more wxWidgets classes have been added/exposed).
