### ISSUE TITLE
Segmentation faults on OSX 64-bit builds

### ISSUE THREAD

**Issue by chymanfx** [pkulchenko/wxlua#14]
Hi,

I am trying to get wxlua running on 64-bit Mac OSX. I have oriented myself on the ZBS build scripts and on 64-bit Linux everything compiles and runs fine. On both platforms I have used exactly the same sources:

- LuaJIT version 2.0.5 (the latest stable release)
- Lua version 5.1.5
- wxWidgets version 3.0.4 (the latest stable release)
- wxlua (top of wxwidgets311 branch)

On OSX 64-bit everything also compiles well, but tests with wxlua fail on memory management. With Luajit the libwx does not load but fails in wxLuaEvent object destruction and with Lua 5.1 it fails on the "unittest.wx.lua" as soon as the garbagecollector comes into action, see output below.

Could you please let me know if there is a way to fix this? Please let me know if more details are needed.

Many thanks in advance!

Best regards,
chyfx

Attached please find the debugging/test results: [log.txt](https://github.com/pkulchenko/wxlua/files/2041858/log.txt)

**Comment by chymanfx** [comment]
Dear Paul,

thank you for looking into this.

Just a heads-up, I now also got a working wxlua DLL with 64-bit MinGW compiler for the Windows platform.

Please let me know how I can support this issue.

Many thanks!

Kind greetings,
chyfx

**Comment by pkulchenko** [comment]
@chymanfx, I'm curious about what results you get with LuaJIT 2.1 (there have been many changes between 2.0.5 and 2.1) and wxWidgets 3.1.1, which should be the latest released version. I'll be switching to 64bit version on MacOS shortly, so am interested in your results. How did you compile wxwidgets on OSX? What build scripts are you using?

**Comment by chymanfx** [comment]
I have build and tested with LuaJIT 2.1.0-beta3 and also with Lua 5.1.5 both show issues with the GC.

Please see the attached crash files:
[crash_luajit21.txt](https://github.com/pkulchenko/wxlua/files/2344644/crash_luajit21.txt)
[crash_lua515.txt](https://github.com/pkulchenko/wxlua/files/2344643/crash_lua515.txt)

I assume that both are caused by the same problem, only that the GC becomes active at a later time on Lua 5.1.5 and thus triggers the issue somewhat later.

Kind greetings!

**Comment by chymanfx** [comment]
I found a solution to my issue: On linking the libwx library I statically linked in liblua.a (5.1.5), that works fine on Linux, but seems to be an issue for OSX. When linking libwx with dynamic liblua.dylib it also works on OSX.
The fact that the NULL pointer exceptions occurring on calls to lua_gc happened in C++ std library gave me hint to library address space mismatches: lua_gc should only call into C libraries and not into C++ libraries.
