### ISSUE TITLE
cmake cannot determine the wxWidgets_PORTNAME/UNIVNAME/UNICODEFLAG/DEBUGFLAG on MinGW builds

### ISSUE THREAD

**Issue by chymanfx** [pkulchenko/wxlua#15]
Hi,

when compiling wxWidget 3.0.4 with MSYS and MinGW via configure, the wxLua cmake process cannot recognize the wxWidgets_PORTNAME/UNIVNAME/UNICODEFLAG/DEBUGFLAG giving the warning:

**WARNING: Unable to find wxWidgets_PORTNAME/UNIVNAME/UNICODEFLAG/DEBUGFLAG from lib names! You may have to add code to CMake to help it parse your wxWidgets lib names.**

To fix this I added a paragraph to wxLua/build/CMakewxAppLib.cmake:

```
    # wxWidgets lib/dll build using MinGW (libwx_mswu_core-3.0.a)
    if ("${wxWidgets_PORTNAME}" STREQUAL "")
        string(REGEX MATCH "libwx_(msw)(univ)?(u)?(d)?_core-([0-9].[0-9]).a" _match_mingw "${wxWidgets_LIBRARIES}")

        if (NOT "${_match_mingw}" STREQUAL "")
            set(wxWidgets_PORTNAME    "${CMAKE_MATCH_1}" )
            set(wxWidgets_UNIVNAME    "${CMAKE_MATCH_2}" )
            set(wxWidgets_UNICODEFLAG "${CMAKE_MATCH_3}" )
            set(wxWidgets_DEBUGFLAG   "${CMAKE_MATCH_4}" )
            #set(wxWidgets_LIB_VERSION "${CMAKE_MATCH_5}" )
        endif()
    endif()
```
Perhaps it makes sense to add this in the repo as well.

Best regards!

**Comment by pkulchenko** [comment]
Should be closed by #16.
