### ISSUE TITLE
editor.wx.lua with wxWidgets 3.1.1

### ISSUE THREAD

**Issue by sonoro1234** [pkulchenko/wxlua#25]
editor.wx.lua with wxLua compiled with wxWidgets/wxWidgets tag 3.1.1 dont show lua markdown but instead
![clipboard01](https://user-images.githubusercontent.com/1795930/53517757-b15fd600-3acf-11e9-96c1-1b7fb0194949.jpg)

Any clues?

**Comment by pkulchenko** [comment]
@sonoro1234, I'll have to check. I'm using a slightly earlier version of 3.1.1 and don't see this issue.

**Comment by sonoro1234** [comment]
Yes the issue is generated in some commit between your master and tag 3.1.1.
Watching the commits that affect stc didnt give me any clue :-(

**Comment by sonoro1234** [comment]
I have found that SCI_LEXER dont gets defined (Althought it seems to be defined in cmakelist.txt)
https://github.com/wxWidgets/wxWidgets/blob/v3.1.1/build/cmake/lib/stc/CMakeLists.txt#L176
