### ISSUE TITLE
nmake compilation error

### ISSUE THREAD

**Issue by sonoro1234** [pkulchenko/wxlua#26]
Hi Paul,

I have managed to work a bundled solution for building wx module 3.1.1 with cmake, it is part of a superproject and can be found here https://github.com/sonoro1234/Lua2SC/tree/master/wxLuaBundled

Building with mingw works but trying with nmake  I get some warnings in wxWidgets building
```
[ 92%] Building CXX object libs/stc/CMakeFiles/wxscintilla.dir/__/__/__/__/src/stc/scintilla/lexlib/PropSetSim
ple.cxx.obj
cl : L?nea de comandos warning D9025 : invalidando '/EHs' con '/EHa'
```
and finally an error in wxLuaModule building

```
[ 18%] Building CXX object wxlua/wxLua/modules/luamodule/CMakeFiles/wxLuaModule.dir/__/wxbind/src/wxcore_appframe.cpp.obj
        cd C:\supercolliderrepos\build_wxLuaBundled_nmake\wxlua\wxLua\modules\luamodule
        C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1415~1.267\bin\Hostx86\x86\cl.exe @C:\Users\Carmen\AppData\Local\Temp\nm7669.tmp
wxcore_appframe.cpp
C:\Program Files (x86)\Microsoft VisualStudio\2017\Community\VC\Tools\MSVC\14.15.26726\include\xlocale(319):
warning C4530: Se ha utilizado el controlador de excepciones de C++, pero la semántica de desenredo no está habilitada. Especifique /EHsc
C:\supercolliderrepos\Lua2SC\wxLuaBundled\wxlua\wxLua\modules\wxbind\src\wxcore_appframe.cpp(317): error C2039
: 'OnExceptionInMainLoop': no es un miembro de 'wxAppConsole'
C:\supercolliderrepos\build_wxLuaBundled_nmake\wxWidgets_install\include\wx/app.h(546): note: vea la declaración de 'wxAppConsole'
```
(Sorry, some output is in spanish)
It is related to exceptions managing. Should I set some flag?

**Comment by pkulchenko** [comment]
@sonoro1234, it seems like you are using MSVC, which I don't have a recent version to test with. Can you try using the suggested options (`/EHs` or `/EHa`; I'm not sure which one is suggested in the message you are seeing)?

**Comment by sonoro1234** [comment]
The suggeste flag was `/EHsc`

The building has succed when setting  wxDEBUG_LEVEL = 0 as explained for mingw in issue #28
