### ISSUE TITLE
Official repo?

### ISSUE THREAD

**Issue by sonoro1234** [pkulchenko/wxlua#27]
Hi Paul,

This repo seems to be the "official" repo now, as John Labensky has not added more commit to his svn repository since 2016.

Why are you still applying patches to ZeroBraneStudio builds instead of making a commit for it?

I mean as https://github.com/pkulchenko/ZeroBraneStudio/blob/master/build/build-win32.sh#L298

victor bombi

**Comment by pkulchenko** [comment]
This update was made a long time ago (even before this repository was created). I'm less hesitant to apply patches like this to this repository, but I think we need to be aware that while the wxlua code in ZeroBrane Studio is well tested and widely used, it doesn't cover all the modules. For example, the socket wxlua/wxwidgets functionality is not used in ZBS, so I can't be sure that it's not being affected by the patches. I think I've applied most (if not all) other patches to wxlua, so I'm not holding out much.
