### ISSUE TITLE
wxWidgets Debug alert make luajit crash

### ISSUE THREAD

**Issue by sonoro1234** [pkulchenko/wxlua#28]
Is there something I can do to avoid it?
I think this is wxWidget debug alert that does not arrive to wxLua so there is no message about the lua code triggering it, and so it is difficut to track.

wxDisableAsserts seems not wrapped by wxLua

defining wxDEBUG_LEVEL = 0 before wxWidgets compilation seems the only way to get rid of them

**Comment by pkulchenko** [comment]
@sonoro1234, any further details on this? How do you trigger the alert? Any details from the stack trace after the crash?

**Comment by sonoro1234** [comment]
The alert was triggered by lua code: Inserting with CENTER_HORIZONTAL in a wxBoxSizer with horizontal style.

wxWidgets were compiled in debug mode but wxLua with Release mode (my fault).

Still dont have stack trace.

**Comment by sonoro1234** [comment]
I have managed to compile wxWidgets and wxLuaModule with wxDEBUG_LEVEL = 0 and the assertions dissappear avoiding the crash.

It would be much more convenient to wrap wxDisableAsserts function so that we can use asserts or not at will.

**Comment by pkulchenko** [comment]
> I have managed to compile wxWidgets and wxLuaModule with wxDEBUG_LEVEL = 0 and the assertions dissappear avoiding the crash.

@sonoro1234, I use the same configuration for non-debug builds, so not sure what may be going on with the assertions and don't plan to work on this in the near future. Feel free to re-open if you have some additional information or have time to work on this.
