### ISSUE TITLE
idle RequestMore

### ISSUE THREAD

**Issue by sonoro1234** [pkulchenko/wxlua#29]
Comparing my wxLua with 2.8.12 (compiled years ago) and 3.1.1 (which behaves the same as ZeroBraneStudio wx.dll)

Previously the OnIdle function only called RequestMore when it detected than a lanes message had been sent in order to get new lanes messages.
If RequesMore were always called CPU use would increase a lot. (from 1% to 13%)

With 3.1.1 using the previous scheme makes OnIdle not being called at all if the application is not foreground and being called very lazely when it is foreground.

I dont know if its wxWidgets issue or wxLua.
I dont know if the only solution is calling RequestMore always or is there a better one.

**Comment by pkulchenko** [comment]
@sonoro1234, are you saying that `OnIdle` is not generated frequently enough with the newer version? I think the idea behind `RequestMore` is that it's only called when the application needs to do more processing, but doesn't want to block other (likely higher priority) events form being processed.

I can't comment on the differences between wxwidgets 2.8.12 and 3.1, but there have been quite few changes in 3.0 and 3.1, so I wouldn't be surprised that somethings has changes with OnIdle handling. I don't think there have been any changes in wxlua related to that (or at least, I'm not aware of any).

**Comment by sonoro1234** [comment]
> are you saying that `OnIdle` is not generated frequently enough with the newer version?

Not only that but also that they are not generated at all for background windows.

**Comment by pkulchenko** [comment]
I'm not sure when or how this has changed, but you may want to have OnTimer event that is periodically executed to check when the last OnIdle event was and calls whatever logic you need if it was some time ago (or just queues another onIdle event as needed).

This is not really an answer, but may provide a sufficient workaround for most of the cases.

**Comment by sonoro1234** [comment]
This solution works for me. CPU is low 2% instead of 13% with calling always RequestMore

```lua
--instead of requestmore on idle
local ID_TIMERIDLEWAKEUP = 2
wakeupidletimer  = wx.wxTimer(frame,ID_TIMERIDLEWAKEUP)
frame:Connect(wx.wxEVT_TIMER,
		function (event)
			local id=event:GetId()
			if id==ID_TIMERIDLEWAKEUP then
				wx.wxWakeUpIdle()
			end
		end)
wakeupidletimer:Start(30,false)
```
I could not find anything on internet about this OnIdle change
Thanks

**Comment by pkulchenko** [comment]
I haven't seen anything on that either. Glad the timer workaround works for you. You may want to add some check to see if the app is in the background before triggering it, but I suspect that `wxWakeUpIdle` you are using is fairly lightweight, so may not make much difference.
