### ISSUE TITLE
[FR] store wx/STC/stedit/... lib versions during the build

### ISSUE THREAD

**Issue by ildar** [pkulchenko/wxlua#33]
Justification: some libs that wxlua depends on have API changes difficult to guess/control.
The idea is to get the version info during the build and store it in wxlua secret stash (RO table).
Then any client can have this info available during runtime.
Example:
> $ egrep '^#define.*VERSION' /usr/include/wx/stedit/stedefs.h
> #define STE_MAJOR_VERSION      1
> #define STE_MINOR_VERSION      6
> #define STE_RELEASE_VERSION    0
> #define STE_SUBRELEASE_VERSION 0

**Comment by pkulchenko** [comment]
This has been added in 24b86d2c. Closing...
