### ISSUE TITLE
CMake warnings

### ISSUE THREAD

**Issue by sonoro1234** [pkulchenko/wxlua#35]
Only warnings
```
CMake Warning at wxlua/wxLua/build/CMakeFunctions.cmake:586 (MESSAGE):
  Missing directory in
  ADD_SUBDIRECTORY(C:/supercolliderrepos/wxLuaBundled/wxlua/wxLua/modules/wxstedit)
Call Stack (most recent call first):
  wxlua/wxLua/CMakeLists.txt:372 (add_subdirectory)


MINGW_EXTRA_LIBS is -lversion-lshlwapi-luxtheme-loleacc-lws2_32
MINGW_EXTRA_LIBS is -lversion-lshlwapi-luxtheme-loleacc-lws2_32
CMake Warning (dev) at wxlua/wxLua/build/CMakeFunctions.cmake:1010 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "WIN32" will no longer be dereferenced when the
  policy is set to NEW.  Since the policy is not set the OLD behavior will be
  used.
Call Stack (most recent call first):
  wxlua/wxLua/apps/CMakeLists.txt:33 (ADD_EXECUTABLE_FULL)
  wxlua/wxLua/apps/wxlua/CMakeLists.txt:3 (wxLua_Apps_wxLua_TARGETS)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at wxlua/wxLua/build/CMakeFunctions.cmake:1010 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "WIN32" will no longer be dereferenced when the
  policy is set to NEW.  Since the policy is not set the OLD behavior will be
  used.
Call Stack (most recent call first):
  wxlua/wxLua/apps/CMakeLists.txt:63 (ADD_EXECUTABLE_FULL)
  wxlua/wxLua/apps/wxluacan/CMakeLists.txt:3 (wxLua_Apps_wxLuaCan_TARGETS)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- * WARNING: wxLuaEdit application will not be built since wxStEdit was not found.
-- * WARNING: wxStEdit_ROOT_DIR directory does not exist: ''
CMake Warning (dev) at wxlua/wxLua/build/CMakeFunctions.cmake:1010 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "WIN32" will no longer be dereferenced when the
  policy is set to NEW.  Since the policy is not set the OLD behavior will be
  used.
Call Stack (most recent call first):
  wxlua/wxLua/apps/CMakeLists.txt:139 (ADD_EXECUTABLE_FULL)
  wxlua/wxLua/apps/wxluafreeze/CMakeLists.txt:3 (wxLua_Apps_wxLuaFreeze_TARGETS)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by pkulchenko** [comment]
wxstedit hasn't been updated since 2007; I'm not sure what is going to be lost by not including it, but it's not being used in the `luamodule` building. Looks like only wxLuaEdit may be potentially affected.

@sonoro1234, if you know what needs to be updated to address these warnings, I'd love to see the patch, as my cmake skills are a bit limited and I'm having enough fun with extending wxlua to address some of the issues.

**Comment by pkulchenko** [comment]
@sonoro1234, pushed a change that should fix the warnings. Tested locally without issues, but let me know if it causes any problems for you.

**Comment by sonoro1234** [comment]
I have done two builds:
1- with last wxWidgets master 
2- with my fork wxWidgets https://github.com/sonoro1234/wxWidgets/tree/93119082848ad1629180925ee437531cab244aa4

Which should be? I cant find v3.1.3 tag but only v3.1.2

there are linking error on both
`[100%] Linking CXX shared library ..\..\..\..\bin\MinSizeRel\wx.dll
cd /d C:\supercolliderrepos\build_wxLuaBundled2\wxlua\wxLua\modules\luamodule && C:\cmake-3.13.0-rc1-win64-x64\bin\cmake.exe
-E cmake_link_script CMakeFiles\wxLuaModule.dir\link.txt --verbose=1
C:\cmake-3.13.0-rc1-win64-x64\bin\cmake.exe -E remove -f CMakeFiles\wxLuaModule.dir/objects.a
C:\i686-7.2.0-release-posix-dwarf-rt_v5-rev1\mingw32\bin\ar.exe cr CMakeFiles\wxLuaModule.dir/objects.a @CMakeFiles\wxLuaModu
le.dir\objects1.rsp
C:\i686-7.2.0-release-posix-dwarf-rt_v5-rev1\mingw32\bin\g++.exe  -DLUA_COMPAT_MODULE -DwxDEBUG_LEVEL=0  -Wall -Os -DNDEBUG
-shared -o ..\..\..\..\bin\MinSizeRel\wx.dll -Wl,--out-implib,..\..\..\..\lib\MinSizeRel\libwx.dll.a -Wl,--major-image-versio
n,0,--minor-image-version,0 -Wl,--whole-archive CMakeFiles\wxLuaModule.dir/objects.a -Wl,--no-whole-archive @CMakeFiles\wxLua
Module.dir\linklibs.rsp
../../../../build_wx/install/lib/gcc_lib/wxmsw31u_stc.a(stc.cpp.obj):stc.cpp:(.text+0x1921): undefined reference to `Scintill
a_LinkLexers'
../../../../build_wx/install/lib/gcc_lib/wxmsw31u_stc.a(stc.cpp.obj):stc.cpp:(.text+0x1b91): undefined reference to `Scintill
a_LinkLexers'
../../../../build_wx/install/lib/gcc_lib/wxmsw31u_stc.a(ScintillaWX.cpp.obj):ScintillaWX.cpp:(.text+0x316): undefined referen
ce to `Editor::SetDragPosition(SelectionPosition)'
../../../../build_wx/install/lib/gcc_lib/wxmsw31u_stc.a(ScintillaWX.cpp.obj):ScintillaWX.cpp:(.text+0x482): undefined referen
ce to `Selection::Empty() const'
../../../../build_wx/install/lib/gcc_lib/wxmsw31u_stc.a(ScintillaWX.cpp.obj):ScintillaWX.cpp:(.text+0x4ca): undefined referen
ce to `Editor::CopySelectionRange(SelectionText*, bool)'
../../../../build_wx/install/lib/gcc_lib/wxmsw31u_stc.a(ScintillaWX.cpp.obj):ScintillaWX.cpp:(.text+0x62c): undefined referen
ce to `Editor::GetTextRectangle() const'
../../../../build_wx/install/lib/gcc_lib/wxmsw31u_stc.a(ScintillaWX.cpp.obj):ScintillaWX.cpp:(.text+0x73e): undefined referen
ce to `Editor::Wrapping() const'
../../../../build_wx/install/lib/gcc_lib/wxmsw31u_stc.a(ScintillaWX.cpp.obj):ScintillaWX.cpp:(.text+0x849): undefined referen
ce to `Editor::HorizontalScrollTo(int)'
../../../../build_wx/install/lib/gcc_lib/wxmsw31u_stc.a(ScintillaWX.cpp.obj):ScintillaWX.cpp:(.text+0xbad): undefined referen
ce to `Editor::PointMainCaret()'
../../../../build_wx/install/lib/gcc_lib/wxmsw31u_stc.a(ScintillaWX.cpp.obj):ScintillaWX.cpp:(.text+0x16fd): undefined refere
nce to `Editor::PositionFromLocation(Point, bool, bool)'
../../../../build_wx/install/lib/gcc_lib/wxmsw31u_stc.a(ScintillaWX.cpp.obj):ScintillaWX.cpp:(.text+0x1712): undefined refere
nce to `Editor::SetDragPosition(SelectionPosition)'
../../../../build_wx/install/lib/gcc_lib/wxmsw31u_stc.a(ScintillaWX.cpp.obj):ScintillaWX.cpp:(.text+0x177c): undefined refere
nce to `Editor::PositionFromLocation(Point, bool, bool)'
../../../../build_wx/install/lib/gcc_lib/wxmsw31u_stc.a(ScintillaWX.cpp.obj):ScintillaWX.cpp:(.text+0x182f): undefined refere
nce to `ScintillaBase::ScintillaBase()'
../../../../build_wx/install/lib/gcc_lib/wxmsw31u_stc.a(ScintillaWX.cpp.obj):ScintillaWX.cpp:(.text+0x201e): undefined refere`

**Comment by sonoro1234** [comment]
The cause seems to be the commit: remove explicit adition of scintilla

**Comment by pkulchenko** [comment]
@sonoro1234, yes, can you try the following patch:

```diff
diff --git a/wxLua/build/FindwxWidgets.cmake b/wxLua/build/FindwxWidgets.cmake
index aadc4bd..81b4487 100644
--- a/wxLua/build/FindwxWidgets.cmake
+++ b/wxLua/build/FindwxWidgets.cmake
@@ -262,7 +262,7 @@ if(wxWidgets_FIND_STYLE STREQUAL "win32")
     # FIXME: What if both regex libs are available. regex should be
     # found outside the loop and only wx${LIB}${_UCD}${_DBG}.
     # Find wxWidgets common libraries.
-    foreach(LIB ${wxWidgets_COMMON_LIBRARIES})
+    foreach(LIB ${wxWidgets_COMMON_LIBRARIES} scintilla)
       unset(WX_${LIB}${_DBG} CACHE) # jl - Must unset if they choose msw then wanted mswu
       find_library(WX_${LIB}${_DBG}
         NAMES
```

I wanted to remove the dependency on the wrong name of the scintilla library, but it's possible that removed too much. I tested on my Windows box as well as on Linux and macOS and didn't get any linker issues. Please add that reference back and re-compile.

The current wxwidgets master is 3.1.3, as that's what it will be labeled with upon release.

**Comment by sonoro1234** [comment]
I am not able to apply patch but I was able to build if I use wxLua before that commit

**Comment by sonoro1234** [comment]
The patch seems not enough because that commit also changed \wxLua\build\CMakewxAppLib.cmake

reverting just this commit linking succeds

**Comment by pkulchenko** [comment]
@sonoro1234, yes, #30 was fixed in wxWidgets.

Can you apply the patch manually (just modify the one line that was changed by adding `scintilla` to it)? I do know that reverting the commit fixes it, but I don't want to fully revert the commit. Or do you mean you already tried and it didn't work?

Can you make sure you do the test on a clean copy of wxlua (so the makefiles are regenerated properly)? You may need to run `git checkout .` and `git clean -fd` (this command will remove all files that are not in the wxlua repository, so make sure you save anything you need in the tree).

**Comment by sonoro1234** [comment]
>Or do you mean you already tried and it didn't work?

Yes.

Now deleted repo and git clone again, added scintilla (as in the patch), run cmake and make but linking failed (doesnt seem enough)

**Comment by pkulchenko** [comment]
ok; thank you; let me try couple of things...

**Comment by sonoro1234** [comment]
When buildin last wxWidgets master there are zillions of warnings as
`[ 75%] Building CXX object libs/html/CMakeFiles/html.dir/__/__/__/__/src/html/htmlcell.cpp.obj
In file included from C:/supercolliderrepos/wxLuaBundled/wxWidgets/include/wx/font.h:659:0,
                 from C:/supercolliderrepos/wxLuaBundled/wxWidgets/include/wx/dc.h:22,
                 from C:\supercolliderrepos\wxLuaBundled\wxWidgets\src\html\htmlcell.cpp:21:
C:/supercolliderrepos/wxLuaBundled/wxWidgets/include/wx/msw/font.h: In constructor 'wxFont::wxFont(int, int, int, int, bool,
const wxString&, wxFontEncoding)':
C:/supercolliderrepos/wxLuaBundled/wxWidgets/include/wx/msw/font.h:135:5: warning: 'wxFont::wxFont(int, int, int, int, bool,
const wxString&, wxFontEncoding)' is deprecated: use wxFONT{FAMILY,STYLE,WEIGHT}_XXX constants ie: wxFONTFAMILY_SWISS, wxFONT
STYLE_NORMAL, wxFONTWEIGHT_BOLD [-Wdeprecated-declarations]
     }
     ^
C:/supercolliderrepos/wxLuaBundled/wxWidgets/include/wx/msw/font.h:126:5: note: declared here
     wxFont(int size,
     ^~~~~~
C:/supercolliderrepos/wxLuaBundled/wxWidgets/include/wx/msw/font.h: In constructor 'wxFont::wxFont(int, int, int, int, bool,
const wxString&, wxFontEncoding)':
C:/supercolliderrepos/wxLuaBundled/wxWidgets/include/wx/msw/font.h:135:5: warning: 'wxFont::wxFont(int, int, int, int, bool,
const wxString&, wxFontEncoding)' is deprecated: use wxFONT{FAMILY,STYLE,WEIGHT}_XXX constants ie: wxFONTFAMILY_SWISS, wxFONT
STYLE_NORMAL, wxFONTWEIGHT_BOLD [-Wdeprecated-declarations]
     }
     ^
C:/supercolliderrepos/wxLuaBundled/wxWidgets/include/wx/msw/font.h:126:5: note: declared here
     wxFont(int size,
     ^~~~~~
C:/supercolliderrepos/wxLuaBundled/wxWidgets/include/wx/msw/font.h: In constructor 'wxFont::wxFont(const wxSize&, int, int, i
nt, bool, const wxString&, wxFontEncoding)':
C:/supercolliderrepos/wxLuaBundled/wxWidgets/include/wx/msw/font.h:148:5: warning: 'wxFont::wxFont(const wxSize&, int, int, i
nt, bool, const wxString&, wxFontEncoding)' is deprecated: use wxFONT{FAMILY,STYLE,WEIGHT}_XXX constants ie: wxFONTFAMILY_SWI
SS, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_BOLD [-Wdeprecated-declarations]
     }
     ^
C:/supercolliderrepos/wxLuaBundled/wxWidgets/include/wx/msw/font.h:138:5: note: declared here
     wxFont(const wxSize& pixelSize,
     ^~~~~~
C:/supercolliderrepos/wxLuaBundled/wxWidgets/include/wx/msw/font.h: In constructor 'wxFont::wxFont(const wxSize&, int, int, i
nt, bool, const wxString&, wxFontEncoding)':
C:/supercolliderrepos/wxLuaBundled/wxWidgets/include/wx/msw/font.h:148:5: warning: 'wxFont::wxFont(const wxSize&, int, int, i
nt, bool, const wxString&, wxFontEncoding)' is deprecated: use wxFONT{FAMILY,STYLE,WEIGHT}_XXX constants ie: wxFONTFAMILY_SWI
SS, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_BOLD [-Wdeprecated-declarations]
     }
     ^
C:/supercolliderrepos/wxLuaBundled/wxWidgets/include/wx/msw/font.h:138:5: note: declared here
     wxFont(const wxSize& pixelSize,
     ^~~~~~
In file included from C:/supercolliderrepos/wxLuaBundled/wxWidgets/include/wx/wxprec.h:12:0,
                 from C:\supercolliderrepos\wxLuaBundled\wxWidgets\src\html\htmlcell.cpp:9:
C:/supercolliderrepos/wxLuaBundled/wxWidgets/include/wx/image.h: In constructor 'wxImage::wxImage(const wxString&, long int,
int)':
C:/supercolliderrepos/wxLuaBundled/wxWidgets/include/wx/image.h:543:9: warning: 'wxImage::wxImage(const wxString&, long int,
int)' is deprecated [-Wdeprecated-declarations]
         }
         ^
C:/supercolliderrepos/wxLuaBundled/wxWidgets/include/wx/defs.h:611:43: note: in definition of macro 'wxDEPRECATED'
 #define wxDEPRECATED(x) wxDEPRECATED_DECL x`

Are they related to `--enable-compat28`?

**Comment by pkulchenko** [comment]
Yes, I switched to `--enable-compat30` in my builds. Are you still using `compat28`?

**Comment by pkulchenko** [comment]
@sonoro1234, can you go back to the configuration that results in the build error and check the values for `wxLuaLib_LIB_DEPENDS` and `wxLuaModule_LIB_DEPENDS` in `wxLua/CMakeCache.txt`? They should both include references to `wxscintilla-3.1` .

Also, how does your `cmake` command in this configuration look like?

**Comment by pkulchenko** [comment]
@sonoro1234, also, can you show the content of the file `CMakeFiles\wxLuaModule.dir\link.txt` on the build that fails to link (using the current wxlua master)?

**Comment by sonoro1234** [comment]
> @sonoro1234, can you go back to the configuration that results in the build error and check the values for `wxLuaLib_LIB_DEPENDS` and `wxLuaModule_LIB_DEPENDS` in `wxLua/CMakeCache.txt`? They should both include references to `wxscintilla-3.1` .

They dont:

`wxLuaLib_LIB_DEPENDS:STATIC=general;LuaLib;general;C:/supercolliderrepos/build_wxLuaBundled/build_wx/install/lib/gcc_lib/wxmsw31u_stc.a;general;C:/supercolliderrepos/build_wxLuaBundled/build_wx/install/lib/gcc_lib/wxmsw31u_gl.a;general;C:/supercolliderrepos/build_wxLuaBundled/build_wx/install/lib/gcc_lib/wxmsw31u_html.a;general;C:/supercolliderrepos/build_wxLuaBundled/build_wx/install/lib/gcc_lib/wxmsw31u_aui.a;general;C:/supercolliderrepos/build_wxLuaBundled/build_wx/install/lib/gcc_lib/wxmsw31u_adv.a;general;C:/supercolliderrepos/build_wxLuaBundled/build_wx/install/lib/gcc_lib/wxmsw31u_core.a;general;C:/supercolliderrepos/build_wxLuaBundled/build_wx/install/lib/gcc_lib/wxbase31u_net.a;general;C:/supercolliderrepos/build_wxLuaBundled/build_wx/install/lib/gcc_lib/wxbase31u.a;general;C:/supercolliderrepos/build_wxLuaBundled/build_wx/install/lib/gcc_lib/libwxpng.a;general;C:/supercolliderrepos/build_wxLuaBundled/build_wx/install/lib/gcc_lib/libwxtiff.a;general;C:/supercolliderrepos/build_wxLuaBundled/build_wx/install/lib/gcc_lib/libwxjpeg.a;general;C:/supercolliderrepos/build_wxLuaBundled/build_wx/install/lib/gcc_lib/libwxzlib.a;general;C:/supercolliderrepos/build_wxLuaBundled/build_wx/install/lib/gcc_lib/libwxregexu.a;general;C:/supercolliderrepos/build_wxLuaBundled/build_wx/install/lib/gcc_lib/libwxexpat.a;general;opengl32;general;glu32;general;winmm;general;comctl32;general;rpcrt4;general;wsock32;`

`wxLuaModule_LIB_DEPENDS:STATIC=general;LuaLib;general;C:/supercolliderrepos/build_wxLuaBundled/build_wx/install/lib/gcc_lib/wxmsw31u_stc.a;general;C:/supercolliderrepos/build_wxLuaBundled/build_wx/install/lib/gcc_lib/wxmsw31u_gl.a;general;C:/supercolliderrepos/build_wxLuaBundled/build_wx/install/lib/gcc_lib/wxmsw31u_html.a;general;C:/supercolliderrepos/build_wxLuaBundled/build_wx/install/lib/gcc_lib/wxmsw31u_aui.a;general;C:/supercolliderrepos/build_wxLuaBundled/build_wx/install/lib/gcc_lib/wxmsw31u_adv.a;general;C:/supercolliderrepos/build_wxLuaBundled/build_wx/install/lib/gcc_lib/wxmsw31u_core.a;general;C:/supercolliderrepos/build_wxLuaBundled/build_wx/install/lib/gcc_lib/wxbase31u_net.a;general;C:/supercolliderrepos/build_wxLuaBundled/build_wx/install/lib/gcc_lib/wxbase31u.a;general;C:/supercolliderrepos/build_wxLuaBundled/build_wx/install/lib/gcc_lib/libwxpng.a;general;C:/supercolliderrepos/build_wxLuaBundled/build_wx/install/lib/gcc_lib/libwxtiff.a;general;C:/supercolliderrepos/build_wxLuaBundled/build_wx/install/lib/gcc_lib/libwxjpeg.a;general;C:/supercolliderrepos/build_wxLuaBundled/build_wx/install/lib/gcc_lib/libwxzlib.a;general;C:/supercolliderrepos/build_wxLuaBundled/build_wx/install/lib/gcc_lib/libwxregexu.a;general;C:/supercolliderrepos/build_wxLuaBundled/build_wx/install/lib/gcc_lib/libwxexpat.a;general;opengl32;general;glu32;general;winmm;general;comctl32;general;rpcrt4;general;wsock32;general;-lversion;general;-lshlwapi;general;-luxtheme;general;-loleacc;general;-lws2_32;`








> Also, how does your `cmake` command in this configuration look like?

This is my cmake command

`"cmake"  -G"MinGW Makefiles"  -DCMAKE_BUILD_TYPE="MinSizeRel"  -DLUA_INCLUDE_DIR="C:/luaGL/sources/lua-5.1.5/src" -DLUA_LIBRARY="C:/anima/Lua51.dll" ../wxLuaBundled`

But this invokes CMakeLists.txt inside wxLuaBundled
https://github.com/sonoro1234/Lua2SC/blob/master/wxLuaBundled/CMakeLists.txt



> @sonoro1234, also, can you show the content of the file `CMakeFiles\wxLuaModule.dir\link.txt` on the build that fails to link (using the current wxlua master)?

It is on another location because of my bundled build, this is the content:

`C:\cmake-3.13.0-rc1-win64-x64\bin\cmake.exe -E remove -f CMakeFiles\wxLuaModule.dir/objects.a
C:\i686-7.2.0-release-posix-dwarf-rt_v5-rev1\mingw32\bin\ar.exe cr CMakeFiles\wxLuaModule.dir/objects.a @CMakeFiles\wxLuaModule.dir\objects1.rsp
C:\i686-7.2.0-release-posix-dwarf-rt_v5-rev1\mingw32\bin\g++.exe  -DLUA_COMPAT_MODULE -DwxDEBUG_LEVEL=0  -Wall -Os -DNDEBUG  -shared -o ..\..\..\..\bin\MinSizeRel\wx.dll -Wl,--out-implib,..\..\..\..\lib\MinSizeRel\libwx.dll.a -Wl,--major-image-version,0,--minor-image-version,0 -Wl,--whole-archive CMakeFiles\wxLuaModule.dir/objects.a -Wl,--no-whole-archive @CMakeFiles\wxLuaModule.dir\linklibs.rsp`

**Comment by sonoro1234** [comment]
> Yes, I switched to `--enable-compat30` in my builds. Are you still using `compat28`?

I could not find info about that in this repo
And in ZB repo
https://github.com/pkulchenko/ZeroBraneStudio/blob/master/build/build-win32.sh#L277
still uses 2.8

All my settings are in https://github.com/sonoro1234/Lua2SC/blob/master/wxLuaBundled/CMakeLists.txt

**Comment by pkulchenko** [comment]
@sonoro1234, this is strange, as the list of (dependency) libraries look completely different. In your case it's: `C:/supercolliderrepos/build_wxLuaBundled/build_wx/install/lib/gcc_lib/libwxpng.a;general;C:/supercolliderrepos/build_wxLuaBundled/build_wx/install/lib/gcc_lib/libwxtiff.a;general;C:/supercolliderrepos/build_wxLuaBundled/build_wx/install/lib/gcc_lib/libwxjpeg.a;general;C:/supercolliderrepos/build_wxLuaBundled/build_wx/install/lib/gcc_lib/libwxzlib.a;general;C:/supercolliderrepos/build_wxLuaBundled/build_wx/install/lib/gcc_lib/libwxregexu.a;general;C:/supercolliderrepos/build_wxLuaBundled/build_wx/install/lib/gcc_lib/libwxexpat.a;general;opengl32;general;glu32;general;winmm;general;comctl32;general;rpcrt4;general;wsock32;` and in mine it is `-lopengl32;general;-lglu32;general;-lwxtiff-3.1;general;-lwxjpeg-3.1;general;-lwxpng-3.1;general;-lwxregexu-3.1;general;-lwxscintilla-3.1;general;-lwxexpat-3.1;general;-lwxzlib-3.1;general;-lrpcrt4;general;-loleaut32;general;-lole32;general;-luuid;general;-luxtheme;general;-lwinspool;general;-lwinmm;general;-lshell32;general;-lshlwapi;general;-lcomctl32;general;-lcomdlg32;general;-ladvapi32;general;-lversion;general;-lwsock32;general;-lgdi32;general;-loleacc;`

Note that my libraries include -3.1 references and list `wxscintilla-3.1`, which your list doesn't.

This list actually comes from wxwidgets; can you execute `bash wx-config --libs` and include the output?

The only difference I see is that I use `cmake -G "MSYS Makefiles"` and you use `"cmake" -G"MinGW Makefiles"`.

When I tried `MinGW Makefiles`, I got the following message, that's why I switched to "MSYS Makefiles":

```
  sh.exe was found in your PATH, here:

  D:/utils/msys64/usr/bin/sh.exe

  For MinGW make to work correctly sh.exe must NOT be in your path.

  Run cmake from a shell that does not have sh.exe in your PATH.

  If you want to use a UNIX shell, then use MSYS Makefiles.
```

**Comment by sonoro1234** [comment]
> can you execute `bash wx-config --libs` and include the output?

No because it would require MSYS which I dont use.
To build with `MinGW Makefiles` you dont have to use MSYS but only mingw-w64 compiler in you path, run cmake and then `mingw32-make install`

**Comment by pkulchenko** [comment]
There has to be a way to execute wx-config, as it's referenced in your cmake file: `${WX_BUILD}/bin/wx-config`. What's the output of it executed in your environment?

**Comment by sonoro1234** [comment]
Because this cmake file is for windows and linux (But i am on windows now with mingw)

**Comment by sonoro1234** [comment]
Linking works now!!
