### ISSUE TITLE
Feature request: Add Lua 5.3

### ISSUE THREAD

**Issue by ValeryKV** [pkulchenko/wxlua#40]
Please add Lua 5.3 to modules. 

> Or could you explain how to do it. I added src, but it is not clear how to add luaproxydll.

**Comment by pkulchenko** [comment]
> Please add Lua 5.3 to modules.

@ValeryKV, I don't plan to, as you can easily compile wxlua using external Lua. Also, Lua 5.4 is going to be out soon and will need to be added and supported.

> Or could you explain how to do it. I added src, but it is not clear how to add luaproxydll.

luaproxydll is rarely needed (mostly when you want to load external modules with a statically compiled Lua interpreter), but if you indeed need it for Lua 5.3, you can follow the "instructions" in `modules/luaproxydll` folder: (1) generate the export file (similar to `proxydll_exports_lua52.h`) using `pexports`, `dumpbin` or similar command running it on lua53.dll, (2) compile `proxydll.c` to generate the binary. See the detailed instructions at the top of the `proxydll.c` file.
