### ISSUE TITLE
How can I use wxGraphicsContext.GetTextExtent()?

### ISSUE THREAD

**Issue by toshinagata** [pkulchenko/wxlua#50]
Hi, @pkulchenko, I am trying to use wxGraphicsContext and having a problem. I want to use wxGraphicsContext.GetTextExtent(), but how? The following code does not work.

```
  frame = wx.wxFrame(wx.NULL, wx.wxID_ANY, "", wx.wxDefaultPosition, wx.wxSize(800, 600))
  local gc = wx.wxGraphicsContext.Create(frame)
  font = gc:CreateFont(wx.wxFont(10, wx.wxFONTFAMILY_SWISS, wx.wxFONTSTYLE_NORMAL, wx.wxFONTWEIGHT_NORMAL), wx.wxBLACK)
  gc:SetFont(font)
  local tw, th = gc:GetTextExtent("TEXT")  --  This does not work
```

wxcore_graphics.cpp shows that GetTextExtent() accepts wxDouble arguments, but is there a way to create a wxDouble object and pass it to GetTextExtent()?

**Comment by pkulchenko** [comment]
@toshinagata, should be fixed now.

**Comment by toshinagata** [comment]
@pkulchenko, thank you for the quick fix!
