### ISSUE TITLE
make install does not install wxluasetup.h (linux)

### ISSUE THREAD

**Issue by sheetcam** [pkulchenko/wxlua#56]
`dest=some_dir`
`cmake ../wxLua -DwxWidgets_CONFIG_EXECUTABLE=$dest/bin/wx-config -DCMAKE_INSTALL_PREFIX=$dest -DCMAKE_BUILD_TYPE=MinSizeRel -DwxLua_LUA_LIBRARY_VERSION=5.2`
`  make -j5`
`  make install`
wxLua/modules/wxbind/setup/wxluasetup.h is not copied to $dest/include

**Comment by pkulchenko** [comment]
@sheetcam, what exactly is it used for? What process is missing the file?

Do you have a patch that fixes this?

**Comment by sheetcam** [comment]
It is needed if you are embedding wxLua in an application. I have no experience with creating cmake files but the attached seems to work.
[diff.txt](https://github.com/pkulchenko/wxlua/files/4102940/diff.txt)

**Comment by pkulchenko** [comment]
@sheetcam, merged; thank you for the patch!
