### ISSUE TITLE
Embed wxLua into a C++ application

### ISSUE THREAD

**Issue by yvan-burrie** [pkulchenko/wxlua#62]
I'm currently creating a C++ application using wxWidgets. I already have Lua 5.3 embedded into it. But I'm planning on adding a feature for user-created plugins. These plugins should allow creating panels and dialogs from wxLua which will be manipulated by the wxWidgets frame or app.

I read the document that outlines "Embedding wxLua in a C++ application" found in section 5.3 of `docs/install.txt` which describes the modules needed. However, I'm having trouble including these modules into my application.

Do you have examples of how I can achieve this using CMake or C++? And how do I hook or register wxLua tables and functions to at least a C++ wxWidgets app?

**Comment by pkulchenko** [comment]
@yvan-burrie, you can take a look at the cmake/build command for ZeroBrane Studio, which builds the libraries and allows Lua code to access wxwidgets API. Here is the command for building wxlua (after wxwidgets is already built): https://github.com/pkulchenko/ZeroBraneStudio/blob/master/build/build-win32.sh#L307

**Comment by yvan-burrie** [comment]
Thanks a lot! I'm looking through it.
