### ISSUE TITLE
Offer up to date binary releases

### ISSUE THREAD

**Issue by soapdog** [pkulchenko/wxlua#65]
Thanks for all the hard work on wxLua.

I've noticed that this repo is more up to date than the wxLua sourceforge page. Would you consider making new up to date binary releases? Thanks.

**Comment by pkulchenko** [comment]
@soapdog, I don't plan to provide binary releases at this time. Given the number of combinations between the versions of Lua supported, the versions of wxwidgets, monolithic library or not, platforms, compilers (VS, gcc, clang), and architectures (32bit, 64bit, aarch64, and others) there are just too many combinations to build, test and support, even when filtering out less popular ones. This doesn't even cover different combinations of wxlua components (gl, webview, and others) that may or may not be included in the library.

**Comment by sonoro1234** [comment]
@pkulchenko perhaps @soapdog is not aware of https://studio.zerobrane.com/ existence. 
wx module can be downloaded from there with all the zerobrane distribution.

**Comment by pkulchenko** [comment]
@sonoro1234, thank you for the reminder. @soapdog, that's correct, there is a binary version of wxlua for Windows/Linux/macOS available, but only for lua 5.1 (although the included scripts can build it for Lua 5.2, 5.3, and 5.4 as well).

**Comment by soapdog** [comment]
@pkulchenko and @sonoro1234, thanks a lot for the replies. I understand, it was just a suggestion. I've been trying to compile it myself here but am facing some troubles, that's why I asked. My troubles are probably due to working with a new ISA, I'm running Windows on ARM64 hardware but if I come with a patch, I'm sure to send a PR.

Thanks again for the help, I have zerobrane studio here, I never thought about extracting wxLua from it, now in hindsight it is quite obvious.

**Comment by pkulchenko** [comment]
@soapdog, sounds good. Don't hesitate to send a PR if you figure out how to fix your issue.
