### ISSUE TITLE
GetTimes in filename.h and wxS_DIR_DEFAULT in filefn.h, running on Win10 

### ISSUE THREAD

**Issue by decuant** [pkulchenko/wxlua#68]
Hi,

the Lua compiler complains about a constant not defined

wxS_DIR_DEFAULT in filename.h (enum wxPosixPermissions in filefn.h)

it's confusing, in wxLua documentation I find this

#define wxS_IRUSR
#define wxS_IWUSR
#define wxS_IXUSR
#define wxS_IRGRP
#define wxS_IWGRP
#define wxS_IXGRP
#define wxS_IROTH
#define wxS_IWOTH
#define wxS_IXOTH
#define wxS_DEFAULT

in filefn.h

enum wxPosixPermissions
{
    /// Standard POSIX names for these permission flags with "wx" prefix.
    //@{
    wxS_IRUSR = 00400,
    wxS_IWUSR = 00200,
    wxS_IXUSR = 00100,

    wxS_IRGRP = 00040,
    wxS_IWGRP = 00020,
    wxS_IXGRP = 00010,

    wxS_IROTH = 00004,
    wxS_IWOTH = 00002,
    wxS_IXOTH = 00001,
    //@}

    /// Longer but more readable synonyms for the constants above.
    //@{
    wxPOSIX_USER_READ = wxS_IRUSR,
    wxPOSIX_USER_WRITE = wxS_IWUSR,
    wxPOSIX_USER_EXECUTE = wxS_IXUSR,

    wxPOSIX_GROUP_READ = wxS_IRGRP,
    wxPOSIX_GROUP_WRITE = wxS_IWGRP,
    wxPOSIX_GROUP_EXECUTE = wxS_IXGRP,

    wxPOSIX_OTHERS_READ = wxS_IROTH,
    wxPOSIX_OTHERS_WRITE = wxS_IWOTH,
    wxPOSIX_OTHERS_EXECUTE = wxS_IXOTH,
    //@}

    /// Default mode for the new files: allow reading/writing them to everybody but
    /// the effective file mode will be set after ANDing this value with umask and
    /// so won't include wxS_IW{GRP,OTH} for the default 022 umask value
    wxS_DEFAULT = (wxPOSIX_USER_READ | wxPOSIX_USER_WRITE | \
                   wxPOSIX_GROUP_READ | wxPOSIX_GROUP_WRITE | \
                   wxPOSIX_OTHERS_READ | wxPOSIX_OTHERS_WRITE),

    /// Default mode for the new directories (see wxFileName::Mkdir): allow
    /// reading/writing/executing them to everybody, but just like wxS_DEFAULT
    /// the effective directory mode will be set after ANDing this value with umask
    wxS_DIR_DEFAULT = (wxPOSIX_USER_READ | wxPOSIX_USER_WRITE | wxPOSIX_USER_EXECUTE | \
                       wxPOSIX_GROUP_READ | wxPOSIX_GROUP_WRITE | wxPOSIX_GROUP_EXECUTE | \
                       wxPOSIX_OTHERS_READ | wxPOSIX_OTHERS_WRITE | wxPOSIX_OTHERS_EXECUTE)
};

see it's using the wxPOSIX...

=========================

I'm also getting an unexpected return value from 

bool GetTimes(wxDateTime* dtAccess, wxDateTime* dtMod, wxDateTime* dtCreate) const;

what I get is [userdata(0xcccttgghh, 36] 36 never changes

// %override [bool, wxDateTime dtAccess, wxDateTime dtMod, wxDateTime dtCreate] wxFileName::GetTimes( );
// C++ Func: bool GetTimes(wxDateTime* dtAccess, wxDateTime* dtMod, wxDateTime* dtCreate) const;
bool GetTimes() const;

I don't understand bool GetTimes() const; what's for.

I thus use wxDateTime GetModificationTime() const; which works properly.

thank you

  Antonio

**Comment by decuant** [comment]
Hi Paul,

regarding this issue, I would close it, I had time for testing now and it's only a difference between the documentation and the code.

wxbase_file.i
=============

In GetTimes() the "bool ret" is the last returned value instead of the first as documented.

The order of the other returned values is correct, like the example I'm pasting here:

00059: Query filename ACCESS   [Vieste.json] 2020\05\24\15-18-28
00060: Query filename MODIFIED [Vieste.json] 2020\05\24\11-34-23
00061: Query filename CREATE   [Vieste.json] 2020\05\23\20-19-58

And I have assumed, presumed, that this    bool GetTimes() const;    is just a placeholder.



Regarding the constants not defined

Here is what is defined

#define wxS_IRUSR
#define wxS_IWUSR
#define wxS_IXUSR
#define wxS_IRGRP
#define wxS_IWGRP
#define wxS_IXGRP
#define wxS_IROTH
#define wxS_IWOTH
#define wxS_IXOTH
#define wxS_DEFAULT


Should be

#define wxS_IRUSR
#define wxS_IWUSR
#define wxS_IXUSR
#define wxS_IRGRP
#define wxS_IWGRP
#define wxS_IXGRP
#define wxS_IROTH
#define wxS_IWOTH
#define wxS_IXOTH

#define wxPOSIX_USER_READ
#define wxPOSIX_USER_WRITE
#define wxPOSIX_USER_EXECUTE
#define wxPOSIX_GROUP_READ
#define wxPOSIX_GROUP_WRITE
#define wxPOSIX_GROUP_EXECUTE
#define wxPOSIX_OTHERS_READ
#define wxPOSIX_OTHERS_WRITE
#define wxPOSIX_OTHERS_EXECUTE

#define wxS_DEFAULT
#define wxS_DIR_DEFAULT					<--- missing


You may want to correct it and close the ticket.

Thank you

   Antonio

**Comment by pkulchenko** [comment]
> And I have assumed, presumed, that this bool GetTimes() const; is just a placeholder.

sort of; it's a "fake" definition that is overridden by a real one that returns `wxDateTime* dtAccess, wxDateTime* dtMod, wxDateTime* dtCreate` (as Lua can't pass parameters by reference).

What you get back is the list of three wxDateTime objects and a boolean (which was the original value).

You can access it as something like this: `wx.wxFileName():GetTimes():FormatISOTime()` (this creates a new wxFileName object, but you'd run it on a real one).

> In GetTimes() the "bool ret" is the last returned value instead of the first as documented.

Yes, I think it's a bug (as it usually puts the original value first), but I'm a bit reluctant to change it now, as it would require a version change. I'll review other cases and if needed switch it when releasing 3.1.

> You may want to correct it and close the ticket.

Agree; will add that.

**Comment by pkulchenko** [comment]
@decuant, I added defines. I won't close the ticket for now, as I want to figure out what to do with the `GetTimes` changes.

**Comment by decuant** [comment]
Hi Paul,

thank you very much for your effort in making wxLua better, me I'm an hobbist and novice with Lua, but I'm using it daily for fun.

Regarding your point if updating the code of GetTimes, I have little to say, in production you should update the comments and not the code, since nobody raised the issue before, otherwise you would break existing projects.

On a design style side, I would correct the code, because makes little sense to have the boolean at the end. But looking at GetModificationTime, then I ask myself if the boolean is of interest at all.

Regards

   Antonio

**Comment by pkulchenko** [comment]
> Regarding your point if updating the code of GetTimes, I have little to say, in production you should update the comments and not the code, since nobody raised the issue before, otherwise you would break existing projects.

Right, that's why I think I would need to bump the version to 3.1 and announce the incompatible API change.

> But looking at GetModificationTime, then I ask myself if the boolean is of interest at all.

It's mostly for compatibility and consistency (as wxlua tends to return "original" wxwidgets results first and then adds its own results for convenience).
