### ISSUE TITLE
wxAuiPaneButton type cast with Lua 5.4

### ISSUE THREAD

**Issue by zuzmo** [pkulchenko/wxlua#69]
Hi, 
I've tried to build wxlua with Lua 5.4-rc3 ( mainly in Zerobrane ). I put the lua source into the modules lib, changed the cmake files, and I've found the next errors>

ZeroBraneStudio/wxlua/wxLua/modules/wxbind/src/wxaui_bind.cpp:11955:44: error: invalid cast from type ‘wxAuiPaneButton*’ to type ‘double’
11955 | if ((double)(lua_Integer)(self->button) == (double)(self->button)) {
      |                                            ^~~~~~~~~~~~~~~~~~~~~~

ZeroBraneStudio/wxlua/wxLua/modules/wxbind/src/wxaui_bind.cpp:11957:30: error: invalid conversion from ‘wxAuiPaneButton*’ to ‘lua_Integer’ {aka ‘long long int’} [-fpermissive]
11957 |     lua_pushinteger(L, self->button);
      |                        ~~~~~~^~~~~~
      |                              |
      |                              wxAuiPaneButton*

ZeroBraneStudio/wxlua/wxLua/modules/wxbind/src/wxaui_bind.cpp:11960:29: error: cannot convert ‘wxAuiPaneButton*’ to ‘lua_Number’ {aka ‘double’}
11960 |     lua_pushnumber(L, self->button);
      |                       ~~~~~~^~~~~~
      |                             |
      |                             wxAuiPaneButton*

Which shows me the wxAuiPaneButton has got a wrong type cast. Can you help me to patch this?

// previously I bugged out the ZeroBraneStudio/wxlua/wxLua/modules/wxlua/wxlstate.cpp:93:34: error: ‘LUA_QL’ was not declared in this scope; did you mean ‘LUA_OK’?
   93 |             return luaL_error(L, LUA_QL("tostring") " must return a string to "
with the change LUA_QL to a simple string

**Comment by pkulchenko** [comment]
@zuzmo, I'll fix LUA_QL issue, but I don't think the first one is related to Lua 5.4. What version of wxwidgets and wxlua are you using to compile this?

**Comment by zuzmo** [comment]
The latest one from your ZB scripts. ( x64 architecture, cmake and g++ are the latest )

**Comment by pkulchenko** [comment]
@zuzmo, I tested with the current master and don't get any issues (other than LUA_QL, which is Lua 5.4-specific).

There was a similar issue that was fixed in #58 (back in February), but it was only applicable if you are using a latest wxwidgets master.

Essentially, using current wxlua master and current wxwidgets master should work. Also using v3.0.0.8 tag and the wxwidgets version retrieved by ZeroBrane Studio build script (commit 1c754fe from https://github.com/pkulchenko/wxWidgets) should work as well (just make sure to get the latest master).

**Comment by zuzmo** [comment]
@pkulchenko have you checked back the fix fo LUA_QL ( and tagged? )

**Comment by pkulchenko** [comment]
@zuzmo, pushed LUA_QL fix. Let me know how it works for you.

**Comment by zuzmo** [comment]
LUA_QL is ok, but  the original errors are the same.

**Comment by pkulchenko** [comment]
@zuzmo, what's your exact configuration? Are you building with the build script in the current master branch of ZeroBrane Studio? if yes, can you apply the following changes to the script?

```diff
diff --git a/build/build-win32.sh b/build/build-win32.sh
index a3bde0e8..35722f5a 100644
--- a/build/build-win32.sh
+++ b/build/build-win32.sh
@@ -288,7 +288,7 @@ if [ $BUILD_WXWIDGETS ]; then
   make $MAKEFLAGS || { echo "Error: failed to build wxWidgets"; exit 1; }
   make install
   cd ..
-  rm -rf "$WXWIDGETS_BASENAME"
+#  rm -rf "$WXWIDGETS_BASENAME"
 fi
 
 # build wxLua
@@ -316,7 +316,7 @@ if [ $BUILD_WXLUA ]; then
   [ -f "$INSTALL_DIR/bin/libwx.dll" ] || { echo "Error: libwx.dll isn't found"; exit 1; }
   [ $DEBUGBUILD ] || strip --strip-unneeded "$INSTALL_DIR/bin/libwx.dll"
   cd ../..
-  rm -rf "$WXLUA_BASENAME"
+#  rm -rf "$WXLUA_BASENAME"
 fi
 
 # build LuaSocket
```

And then run `git describe` command in build/wxWidgets and build/wxlua folders?

Note that the current `master` branch of wxlua will NOT work with pkulchenko/wxWidgets (but it will work with wxwidgets/wxWidgets repository). I still suspect that there is some sort of mix of incompatible versions of wxwidgets/wxlua.

**Comment by zuzmo** [comment]
Well, but the first issue is that I use linux, so I need to patch the build-linux.sh.

Host: Kernel: 5.3.0-53-generic x86_64 bits: 64 compiler: gcc v: 7.5.0 
           Desktop: Cinnamon 4.4.8 wm: muffin dm: LightDM Distro: Linux Mint 19.3 Tricia 
           base: Ubuntu 18.04 bionic 
Graphics:  Device-1: Intel Skylake GT2 [HD Graphics 520] vendor: Dell driver: i915 v: kernel 
           bus ID: 00:02.0 chip ID: 8086:1916 
           Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
           resolution: 1920x1080~60Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics 520 (Skylake GT2) v: 4.5 Mesa 19.2.8 
           compat-v: 3.0 direct render: Yes 
Audio:     Device-1: Intel Sunrise Point-LP HD Audio vendor: Dell driver: snd_hda_intel v: kernel 
           bus ID: 00:1f.3 chip ID: 8086:9d70 
           Sound Server: ALSA v: k5.3.0-53-generic

**Comment by zuzmo** [comment]
Well, with  wxwidgets/wxWidgets works!!! Thanks

**Comment by pkulchenko** [comment]
@zuzmo, sounds good. Thank you for the update.

Just in case someone else runs into this: using current wxlua master and current wxwidgets master should work. Also using v3.0.0.8 tag and the wxwidgets version retrieved by ZeroBrane Studio build script (commit 1c754fe from https://github.com/pkulchenko/wxWidgets) should work as well (just make sure to get the latest master).
