### ISSUE TITLE
[CRASH] ZBS

### ISSUE THREAD

**Issue by ildar** [pkulchenko/wxlua#7]
on top of the issue https://github.com/pkulchenko/wxlua/issues/5 :
ZBS also crashes for me, even when wxGTK/wxstedit/wxLua is built with GTK+2.

> $ gdb lua5.1
(attached below)

**Comment by pkulchenko** [comment]
Is it built with debugging symbols? I see the symbols in the stack trace, but if it's built without debugging support we can't really trust them. If you are building using ZeroBrane Studio scripts, you'll need to add `debug` as an option when you run the build scripts.

Also, what are you doing in the IDE when the crash happens?

**Comment by ildar** [comment]
yes, sorry. I installed debug symbols for wx + wxlua and made a new bt. If
need some more, please let me know.
I suggest that my setup is quite similar to yours except that I use more
fresh source snapshots (and also libwxGTK is solib). (I guess I'll try
closer setup next week).
Meanwhile here's the backtrace. Crash happens on startup, no window appears.
[zbs.gdb.txt](https://github.com/pkulchenko/wxlua/files/1484396/zbs.gdb.txt)

> --
Ildar Mulyukov,
child of God

email: ildar.mulyukov@gmail.com
GoogleTalk: ildar.mulyukov@gmail.com
blog: http://johan-notes.blogspot.com/

**Comment by pkulchenko** [comment]
@ildar, I recompiled using the recent wxwidgets version, but can't reproduce the crash. When you say you use "more fresh source snapshots", do you mean a more recent version of wxwidgets? Can you try on the current master of wxwidgets and the current version of wxwidgets311 branch in wxlua? I'm using build scripts from ZeroBrane Studio project (just comment out `clone` and `rm` commands for wxwidgets and wxlua to re-use the versions you may already have). Let me know if you need more details on how to set it up.

**Comment by ildar** [comment]
Thanks, I'll try next week. Can't spend weekend for that.

**Comment by ildar** [comment]
Paul, sorry for the delay, but I'm back :)
1st off I got ZBS starting again and I'm not sure what exactly changed.
During experiments I changed libs back and forth so something must be
changed right. But..
If you use your build script then I suppose you use GTK+2. Could you please
build wx with GTK+3 just to check? (GTK+3 is officially supported by wx
3.x) Currently I see that GTK2 wx/lua builds working with massive WARNINGS
and works, while GTK3 wx/lua builds WARNING and (with some user actions)
crashing. I suppose that the reason isn't the wxGTK but wxlua.
I'm to close this issue but then
https://github.com/pkulchenko/wxlua/issues/5 should be reopened if you
don't mind.

**Comment by pkulchenko** [comment]
I'll try to build with GTK3, but probably only in a week or two. I remember I ran into several issues with it when I tried to compile last year, but maybe those have been fixed already.
