### ISSUE TITLE
undefined reference to `wxluatype_wxMemoryBuffer'

### ISSUE THREAD

**Issue by Mailaender** [pkulchenko/wxlua#72]
I tried updating to the latest release for @openSUSE but the build fails for me everytime. I am not sure why. Tried different Lua and wxWidgets versions, but it does not seem to matter much.

```
[   27s] [  9%] Linking CXX shared library ../../lib/Release/libwxlua-wx31-3.0.0.8.so
[   28s] /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/wxLuaLib.dir/wxllua.cpp.o: in function `wxluaT_isuserdatatype(lua_State*, int, int)':
[   28s] /home/abuild/rpmbuild/BUILD/wxlua-3.0.0.8/wxLua/modules/wxlua/wxllua.cpp:993: undefined reference to `wxluatype_wxMemoryBuffer'
[   28s] /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/wxLuaLib.dir/wxllua.cpp.o: in function `wxlua_getstringtypelen(lua_State*, int, unsigned long*)':
[   28s] /home/abuild/rpmbuild/BUILD/wxlua-3.0.0.8/wxLua/modules/wxlua/wxllua.cpp:1422: undefined reference to `wxluatype_wxMemoryBuffer'
```

https://build.opensuse.org/package/show/home:Mailaender:branches:devel:languages:lua/wxlua

**Comment by pkulchenko** [comment]
@Mailaender, this looks like a duplicate of #63 with a solution applied in #64. Check if this works for you and I'll make a new release shortly.

**Comment by Mailaender** [comment]
I backported the patch in https://github.com/Mailaender/wxlua/compare/wxmemory-patch and it fixed the compilation error. Thanks!
