### ISSUE TITLE
Compile against Lua 5.4 dies

### ISSUE THREAD

**Issue by alerque** [pkulchenko/wxlua#76]
Excerpt:

```
...
[  8%] Building CXX object modules/wxlua/CMakeFiles/wxLuaLib.dir/wxlstate.cpp.o
/home/caleb/projects/aur/wxlua/src/wxlua-3.0.0.8/wxLua/modules/wxlua/wxlstate.cpp: In function ‘int wxlua_printFunction(lua_State*)’:
/home/caleb/projects/aur/wxlua/src/wxlua-3.0.0.8/wxLua/modules/wxlua/wxlstate.cpp:93:34: error: ‘LUA_QL’ was not declared in this scope; did you mean ‘LUA_OK’?
   93 |             return luaL_error(L, LUA_QL("tostring") " must return a string to "
      |                                  ^~~~~~
      |                                  LUA_OK
```

**Comment by pkulchenko** [comment]
Caleb, can you run it on the current master? I fixed this in e2aa70f59d (#69). Also, see the last comment in #69: https://github.com/pkulchenko/wxlua/issues/69#issuecomment-634729616.

**Comment by alerque** [comment]
Yes master does compile. Can we get a new release tag for this? I can't get Arch Linux stable packages for this (and hence Zerobane Studio) without it. I think there is another problem too because zbstudio doesn't find this even when it *is* compiled for Lua 5.4, but that's bridge 2. For starters a tagged release of this needs to run. I can backport the patch, but it would be nicer to just move forward...

**Comment by pkulchenko** [comment]
Yes, plan to do this shortly; also, as commented in #69, this release will only work with recent versions of wxwidgets (post 3.1.3), due to the API changes, so the ZBS build script will have to be adjusted to use wxwidgets master.

**Comment by alerque** [comment]
Or better yet tag a release of wxwidgets to match ;-)

**Comment by pkulchenko** [comment]
@alerque, pushed 3.0.0.9 that matches the current master. Tagging wxwidgets will be problematic, but I can probably identify the earliest commit in wxwidgets that works with this release. Let me know if you need it.
