### ISSUE TITLE
%rename directive doesn't work on classes

### ISSUE THREAD

**Issue by solemnwarning** [pkulchenko/wxlua#83]
None of the standard bindings use it, but from how it gets used on other things I *think* this syntax is correct:

```
%rename App_SetupHookRegistration class %delete REHex::App::SetupHookRegistration
{
	REHex::App::SetupHookRegistration(REHex::App::SetupPhase phase, const LuaFunction func);
};
```

`genwxbind.lua` compiles the above, but ignores the %rename directive. I had a quick go at patching it to work last night, but couldn't easily figure out how `genwxbind.lua` needed to change. Would be nice just because having classes named rehex.REHex_XXX in Lua is a bit redundant.

**Comment by pkulchenko** [comment]
I reviewed the code in `genwxbind.lua` and there doesn't seem to be any support for applying `%rename` to anything other than methods. By the looks of it, this would be a significant undertaking, so I'm not likely to take on this short term.

**Comment by solemnwarning** [comment]
Fair enough, I wasn't sure if it was *supposed* to work since it got ignored rather than flagged as an error. I might have another look in the future too, but agree on it not being simple to do.

**Comment by pkulchenko** [comment]
Please update/reopen the ticket if you get time for another look.
