### ISSUE TITLE
Unable to build wxLua with wxwidgets 3.1.4

### ISSUE THREAD

**Issue by decuant** [pkulchenko/wxlua#88]
Hello Paul,

since I follow development of wxLua, I noticed that it is true, how somebody else pointed out, that wxLuaCan.exe does not show any icon on the toolbar and I thought you fixed this problem, thus I downloaded the new sources and recompiled the whole lot, but it fails.

```
3>         wxbase_config.cpp
3>     1>
3>C:\wxlua-master\wxLua\modules\wxbind\src\wxbase_bind.cpp(186): error C2065: 'wxBITNESS_32': undeclared identifier
3>     1>
3>C:\wxlua-master\wxLua\modules\wxbind\src\wxbase_bind.cpp(187): error C2065: 'wxBITNESS_64': undeclared identifier
3>     1>
3>C:\wxlua-master\wxLua\modules\wxbind\src\wxbase_bind.cpp(188): error C2065: 'wxBITNESS_INVALID': undeclared identifier
3>     1>
3>C:\wxlua-master\wxLua\modules\wxbind\src\wxbase_bind.cpp(189): error C2065: 'wxBITNESS_MAX': undeclared identifier

```

Is there something I'm missing? Do I have to manually add some variable in the CMake setup?

Thanks

  Antonio

**Comment by pkulchenko** [comment]
`wxBITNESS_32` has been added to wxwidgets 3.1.5, but since it hasn't been released yet, it looks like you are using an earlier snapshot of wxwidgets that doesn't yet have that change. You'll have to use wxwidgets 3.1.4 or get the latest master branch of wxwidgets, as it already includes wxBITNESS changes.

If you still get an error, please include the exact version of wxwidgets and it commit hash if you are building from a repository.

**Comment by decuant** [comment]
Hi Paul,

my copy of wxWidgets is 3.1.4 downloaded from their website, not GitHub. And scanning their sources there's no reference to this platform thing.

I'll keep my binaries as they are and just wait. This means that for the time being I have lost the fix for 'bind' you did.

Thank you for the explanation.

Antonio

**Comment by pkulchenko** [comment]
Can you include the command and the complete output of your wxlua compilation?

**Comment by pkulchenko** [comment]
I'm not sure why you're getting this error, as I just tested wxlua master branch with wxwidgets 3.1.4 on windows and didn't see any issues (everything compiled successfully).

I'd be interested to see the command and the complete output of the compilation to figure out what's going on.

**Comment by decuant** [comment]
Paul,

later today I'm out of home.

**Comment by decuant** [comment]
[output.txt](https://github.com/pkulchenko/wxlua/files/5776836/output.txt)

[CMakeOutput.log](https://github.com/pkulchenko/wxlua/files/5776842/CMakeOutput.log)

[wxLuaLib.vcxproj.txt](https://github.com/pkulchenko/wxlua/files/5776843/wxLuaLib.vcxproj.txt)


Hi Paul,

in order:

1. the output of the build process
2. the CMake I used
3. the Makefile I use for wxlualib (is this what you need?)

**Comment by pkulchenko** [comment]
@decuant, I don't see any wxlua output that is displayed when it's being set up, like the following:

```
-- * Using these wxWidgets components: xrc;xml;stc;gl;html;aui;adv;core;net;base
-- * 
-- * Found wxWidgets :
-- * - wxWidgets_VERSION           = 3.1.5 = 3.1.5
-- * - wxWidgets_COMPONENTS        = xrc;xml;stc;gl;html;aui;adv;core;net;base
-- * - wxWidgets_INCLUDE_DIRS      = D:/users/paul/gits/ZeroBraneStudio/build/deps/lib/wx/include/msw-unicode-static-3.1;D:/users/paul/gits/ZeroBraneStudio/build/deps/include/wx-3.1
-- * - wxWidgets_LIBRARY_DIRS      = 
-- * - wxWidgets_LIBRARIES         = -Ld:/users/paul/gits/ZeroBraneStudio/build/deps/lib;;;-Wl,--subsystem,windows;-mwindows;d:/users/paul/gits/ZeroBraneStudio/build/deps/lib/libwx_mswu_xrc-3.1.a;d:/users/paul/gits/ZeroBraneStudio/build/deps/lib/libwx_mswu_stc-3.1.a;d:/users/paul/gits/ZeroBraneStudio/build/deps/lib/libwx_mswu_gl-3.1.a;d:/users/paul/gits/ZeroBraneStudio/build/deps/lib/libwx_mswu_aui-3.1.a;d:/users/paul/gits/ZeroBraneStudio/build/deps/lib/libwx_baseu_net-3.1.a;d:/users/paul/gits/ZeroBraneStudio/build/deps/lib/libwx_mswu_html-3.1.a;d:/users/paul/gits/ZeroBraneStudio/build/deps/lib/libwx_mswu_core-3.1.a;d:/users/paul/gits/ZeroBraneStudio/build/deps/lib/libwx_baseu_xml-3.1.a;d:/users/paul/gits/ZeroBraneStudio/build/deps/lib/libwx_baseu-3.1.a;-limm32;-lopengl32;-lglu32;-lwxtiff-3.1;-lwxjpeg-3.1;-lwxpng-3.1;-lwxregexu-3.1;-lwxscintilla-3.1;-lwxexpat-3.1;-lwxzlib-3.1;-lrpcrt4;-loleaut32;-lole32;-luuid;-llzma;-luxtheme;-lwinspool;-lwinmm;-lshell32;-lshlwapi;-lcomctl32;-lcomdlg32;-ladvapi32;-lversion;-lwsock32;-lgdi32;-loleacc
-- * - wxWidgets_CXX_FLAGS         = 
-- * - wxWidgets_DEFINITIONS       = _FILE_OFFSET_BITS=64;wxDEBUG_LEVEL=0;__WXMSW__
-- * - wxWidgets_DEFINITIONS_DEBUG = 
-- * - wxWidgets_PORTNAME          = msw
-- * - wxWidgets_UNIVNAME          = 
-- * - wxWidgets_UNICODEFLAG       = u
-- * - wxWidgets_DEBUGFLAG         = 
```

**Comment by decuant** [comment]
Paul,

here it is.

[CMakeLog.txt](https://github.com/pkulchenko/wxlua/files/5777622/CMakeLog.txt)

**Comment by pkulchenko** [comment]
@decuant, should be fixed now. Thank you for the report.
