### ISSUE TITLE
Xcode luac target looks in incorrect location for .o files to link with

### ISSUE THREAD

**Issue by programmingkidx** [pkulchenko/wxlua#89]
I am building wxLua using Xcode. I use CMake to create an Xcode project file. One target that does not build is luac. At the link stage it looks for several .o files in the wrong location. These .o files are from the LuaLib target. 

Doing some detective work I found out the LuaLib .o files are located here: /wxlua/build/modules/lua-5.1/wxLua.build/Debug/LuaLib.build/Objects-normal/arm64/.

The luac target looks for them here: wxlua/build/modules/lua-5.1/CMakeFiles/LuaLib.dir/src/.
This folder does not exist.

Another problem with the Luac target is that it looks for .o files with the ".c" extension still in the name. For example Luac target looks for a file called lmem.c.o. The LuaLib project creates files without the ".c" extension. So there is a lmem.o file but no lmem.c.o file. 

I think the solution to this problem is to change Luac's target search path for the .o files and make sure it looks these files with the ".c" extension removed.

Thank you.

**Comment by programmingkidx** [comment]
The problem appears to be with the variable LuaLib_OBJECT_FILES in the modules/CmakeLists.txt file. This variable lists all the incorrect paths and file names. I can use the string(REPLACE ...) function to make changes to this variable, but I think taking care of the root cause would be better. 

So the question is where is LuaLib_OBJECT_FILES defined?

**Comment by pkulchenko** [comment]
It looks like LuaLib_OBJECT_FILES comes from CMakeFunctions.cmake and is set based on results returned by `GET_OBJECT_FILES`. It looks like it already has `string(REPLACE ".c"   ".obj" fname2 ${fname2})`, so should work correctly, but I'm not sure why it's not happening.

**Comment by pkulchenko** [comment]
Are you by any chance using CMake <= 2.8.4? It looks like it follows a different branch that may not have that replacement...

**Comment by pkulchenko** [comment]
Actually, I take that back. It looks like the replacement only happens for MSVC branch. I see that `*.c.obj` files exist in my configuration as well, but it's not an issue, as they are consistently referenced everywhere, so the resulting library/executable is compiled properly.

What's the actual error you are getting and what's the cmake command you are running?

**Comment by programmingkidx** [comment]
I use the CMake GUI application. It is version 3.19.4. 

When I build the Luac target I see this error:

Build input files cannot be found: '/Users/[...]wxlua/build/modules/lua-5.1/CMakeFiles/LuaLib.dir/src/loadlib.c.o', '/Users/[...]wxlua/build/modules/lua-5.1/CMakeFiles/LuaLib.dir/src/loslib.c.o', '/Users/[...]wxlua/build/modules/lua-5.1/CMakeFiles/LuaLib.dir/src/ldblib.c.o', '/Users/[...]wxlua/build/modules/lua-5.1/CMakeFiles/LuaLib.dir/src/linit.c.o', '/Users/[...]wxlua/build/modules/lua-5.1/CMakeFiles/LuaLib.dir/src/lvm.c.o', '/Users/[...]wxlua/build/modules/lua-5.1/CMakeFiles/LuaLib.dir/src/lcode.c.o', '/Users/[...]wxlua/build/modules/lua-5.1/CMakeFiles/LuaLib.dir/src/ldump.c.o', '/Users/[...]wxlua/build/modules/lua-5.1/CMakeFiles/LuaLib.dir/src/ltm.c.o', '/Users/[...]wxlua/build/modules/lua-5.1/CMakeFiles/LuaLib.dir/src/lobject.c.o', '/Users/[...]wxlua/build/modules/lua-5.1/CMakeFiles/LuaLib.dir/src/lzio.c.o', '/Users/[...]wxlua/build/modules/lua-5.1/CMakeFiles/LuaLib.dir/src/lmathlib.c.o', '/Users/[...]wxlua/build/modules/lua-5.1/CMakeFiles/LuaLib.dir/src/lstring.c.o', '/Users/[...]wxlua/build/modules/lua-5.1/CMakeFiles/LuaLib.dir/src/ltablib.c.o', '/Users/[...]wxlua/build/modules/lua-5.1/CMakeFiles/LuaLib.dir/src/lapi.c.o', '/Users/[...]wxlua/build/modules/lua-5.1/CMakeFiles/LuaLib.dir/src/lstate.c.o', '/Users/[...]wxlua/build/modules/lua-5.1/CMakeFiles/LuaLib.dir/src/ldo.c.o', '/Users/[...]wxlua/build/modules/lua-5.1/CMakeFiles/LuaLib.dir/src/ltable.c.o', '/Users/[...]wxlua/build/modules/lua-5.1/CMakeFiles/LuaLib.dir/src/lfunc.c.o', '/Users/[...]wxlua/build/modules/lua-5.1/CMakeFiles/LuaLib.dir/src/lmem.c.o', '/Users/[...]wxlua/build/modules/lua-5.1/CMakeFiles/LuaLib.dir/src/lundump.c.o', '/Users/[...]wxlua/build/modules/lua-5.1/CMakeFiles/LuaLib.dir/src/ldebug.c.o', '/Users/[...]wxlua/build/modules/lua-5.1/CMakeFiles/LuaLib.dir/src/liolib.c.o', '/Users/[...]wxlua/build/modules/lua-5.1/CMakeFiles/LuaLib.dir/src/lgc.c.o', '/Users/[...]wxlua/build/modules/lua-5.1/CMakeFiles/LuaLib.dir/src/llex.c.o', '/Users/[...]wxlua/build/modules/lua-5.1/CMakeFiles/LuaLib.dir/src/lbaselib.c.o', '/Users/[...]wxlua/build/modules/lua-5.1/CMakeFiles/LuaLib.dir/src/lparser.c.o', '/Users/[...]wxlua/build/modules/lua-5.1/CMakeFiles/LuaLib.dir/src/lauxlib.c.o', '/Users/[...]wxlua/build/modules/lua-5.1/CMakeFiles/LuaLib.dir/src/lopcodes.c.o', '/Users/[...]wxlua/build/modules/lua-5.1/CMakeFiles/LuaLib.dir/src/lstrlib.c.o'

* shortened the paths with [...].

**Comment by pkulchenko** [comment]
> Build input files cannot be found: '/Users/[...]wxlua/build/modules/lua-5.1/CMakeFiles/LuaLib.dir/src/loadlib.c.o'...

@programmingkidx, can you check if the files are actually present in the referenced location? I'm confused why they wouldn't be found if the earlier commands are supposed to generate them.

If this issue is still not resolved, you can install Lua 5.1 yourself and set `-DwxLua_LUA_LIBRARY_USE_BUILTIN=FALSE` along with `-DwxLua_LUA_INCLUDE_DIR` and `-DwxLua_LUA_LIBRARY` pointing to the correct locations for the system library.

**Comment by pkulchenko** [comment]
@programmingkidx, let me know if my suggestions has worked for you or if you have any additional information. I'm closing the ticket, but feel free to continue the discussion and/or to re-open.
